<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Pid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Catagory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[_image]" Member="_image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="user_Product" Member="user" ThisKey="user_id" OtherKey="Uid" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="Uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phone_no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="user_Product" Member="Products" ThisKey="Uid" OtherKey="user_id" Type="Product" />
      <Association Name="user_Post" Member="Posts" ThisKey="Uid" OtherKey="user_id" Type="Post" />
      <Association Name="user_Bid" Member="Bids" ThisKey="Uid" OtherKey="user_id" Type="Bid" />
      <Association Name="user_cart" Member="carts" ThisKey="Uid" OtherKey="User_id" Type="cart" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="PtId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Catagory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[ Image]" Member="_Image" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Post_Bid" Member="Bids" ThisKey="PtId" OtherKey="post_id" Type="Bid" />
      <Association Name="user_Post" Member="user" ThisKey="user_id" OtherKey="Uid" Type="user" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Bid" Member="Bids">
    <Type Name="Bid">
      <Column Name="bId" Member="bId1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="post_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Post_Bid" Member="Post" ThisKey="post_id" OtherKey="PtId" Type="Post" IsForeignKey="true" />
      <Association Name="user_Bid" Member="user" ThisKey="user_id" OtherKey="Uid" Type="user" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.cart" Member="carts">
    <Type Name="cart">
      <Column Name="Cid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="User_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="user_cart" Member="user" ThisKey="User_id" OtherKey="Uid" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>